#
#  Display.
#
source=~/.config/hypr/monitors.conf

#
#  Mouse.
#
input {
	repeat_rate = 30
	sensitivity = -0.5
}

cursor {
    no_hardware_cursors = true
    # Use CPU buffer if the cursor still doesn't show or flickers
    use_cpu_buffer = true 
}


env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

