-- Generated by nwg-displays on 2026-08-15 at 09:21:46. Do not edit manually.

hl.monitor({
    output = "DVI-D-1",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.0,
    transform = 3
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "4880x1266",
    scale = 1
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@100.0",
    position = "1440x906",
    scale = 1
})
