# Single Ultrawide monitor setup
# Automatically detect the preferred resolution and refresh rate for the connected monitor.
monitor=,preferred,auto,1

# Explicit configuration for DP-1 if needed
# monitor=DP-1, preferred, auto, 1
