$terminal=kitty
$file_manager=env QT_QPA_PLATFORMTHEME=kde QT_STYLE_OVERRIDE=breeze dolphin
$menu=rofi -replace -show drun
$calculator=rofi -replace -show calc
$rofi_filemanager=rofi -replace -show filemanager
$discord=discord
$browser=flatpak run app.zen_browser.zen
